[project]
name = "sysadmintoolboxbackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "pip>=24.2",
    "pydantic>=2.9.2",
    "pyjwt>=2.9.0",
    "pytest>=8.3.3",
]
